# 出包 / 暂存共用的「修复标记」表 —— 单一事实源，两个脚本都从这里取。
# 前缀 "!" = 负向标记：这条必须【不在】产物里（守住已回退或不该出现的东西）。

MARKERS = {
    'adapters/via-adapter.js': [
        'decodeHtmlEntities',
        'escapeHtml(node.url',
    ],
    'model/xbel.js': [
        'resolveSyncBucket',
        '扁平根容器',
        'flatRootContainer',
        'wrapperSplicedRemote',
        'isFolderStillFlatWrapper',
        'declaredIsZoneName',
        'bucketTitleForMeta',
        'declaredWrapper',
    ],
    'lib/sync-actions.js': [
        'PERMISSION_API_UNAVAILABLE',
        "'PERMISSION_CHECK_FAILED'",
    ],
    'background.js': [
        "typeof importScripts === 'function'",
        'HAS_BOOKMARKS_API',
        'NO_BOOKMARKS_API',
        'browserAction',
        "case 'ping'",
        "case 'diagnose'",
        'BOOKMARKS_QUERY_TIMEOUT_MS',
        '_bgErrors',
        'persistBootReport',
        'bg_boot_report',
        'recordIncoming',
        'bg_last_message',
        "case 'pingLegacy'",
        '__MiniSyncSelfCheck',
        '__MiniSyncDispatchDirect',
        'onRuntimeMessage',
        'DIRECT_NO_RESPONSE',
        'withTimeout',
        '20s 未返回',
        "manifest.manifest_version === 3) ? 'mv3-service-worker'",
        '_msgLedger',
        'ledgerLookup',
        'msgLedgerReplays',
        'MSG_LEDGER_MAX',
        'clampSyncInterval',
        '__msgId',
    ],
    'lib/utils.js': [
        'PERMISSION_API_UNAVAILABLE',
        'isHandlingUserInput',
        'collectDiagnostics',
        'describeBookmarkCount',
        'describeMessageFailure',
        'getBackgroundPage',
        'backgroundLedger',
        'backgroundLegacyPing',
        'sendMessageToBackground',
        'installSendMessageFallback',
        'rawSendMessage',
        'describeActionStatus',
        'last_write_report',
        'buildTargetOptions',
        'describeTargetValue',
        'pathParts',
        '个书签',
        '__minisyncFallback',
        'BG_DIRECT_TIMEOUT_MS',
        'lastError',
        'bookmarkTreeProbe',
        'zoneByTitle',
        'titlesAvailable',
        'detectFlatRootChild',
        'setDeclaredFlatRootContainer',
        'primeDeclaredFlatRootContainer',
        'getDeclaredFlatRootContainer',
        'resetDeclaredFlatRootContainer',
        'resolveSyncBucket',
        'setSyncBucketId',
        'getSyncBucketId',
        'resetSyncBucketId',
        '__msgId',
        'preferDirect',
        'resetTransportState',
        'createTtlProbe',
        'createCoalescedFetcher',
        'createCoalescedProbe',
        'buildConfigBackup',
        'parseConfigBackup',
        'BACKUP_FIELDS',
        'pickSyncLogRecord',
        'escapeHtml',
        'redactUrlForLog',
        'clampSyncInterval',
        'SYNC_INTERVAL_MIN',
    ],
    'options.js': [
        'describeBookmarkCount',
        'describeMessageFailure',
        'diagBtn',
        'installSendMessageFallback',
        'initBookmarkTargetPicker',
        'bookmark_target_id',
        'initDownloadClearToggle',
        'download_clear',
        'exportConfigBtn',
        'importConfigBtn',
        'parseConfigBackup',
        'createTtlProbe',
        'createCoalescedFetcher',
        'fetchEndpoints',
        'cachedProbe',
        'utils.escapeHtml',
        '本机还没有可导出的配置',
    ],
    'options.html': [
        'diagOut',
        'diagBtn',
        'targetSelect',
        'targetHint',
        'clearCheckbox',
        'clearHint',
        'exportConfigBtn',
        'importConfigBtn',
        'importConfigFile',
        'backupResult',
        'name="viewport" content="width=device-width',
        'id="backupCard"',
        '.btn-primary {',
        '云端删掉的也从本机删掉',
    ],
    'popup.js': [
        'requestHostPermission',
        'describeMessageFailure',
        'installSendMessageFallback',
        'describeActionStatus',
        'recoverSyncResultFromLedger',
        'applySyncResult',
        'SYNC_LOG_ACTION',
        'STATUS_POLL_MAX_TICKS',
        'updateInsecureUrlHint',
        'escapeHtml(new Date',
        'markMobilePopupHost',
        'host-mobile',
        'createCoalescedProbe',
        'statusProbeKey',
        'ENDPOINT_MIRROR_KEYS',
    ],
    'core/sync-orchestrator.js': [
        'last_write_report',
        '没能写入本地',
        'conflictCount',
        'conflictSamples',
        'resolveSyncBucketSetting',
        'targetParentId',
        'download_clear',
        'clearLocalFirst',
        'clearedBefore',
        'wrapperUnwrapped',
        'flatRootContainer',
        'wrapperSpliced',
        'wrapperSplicedRemote',
        'uploadNote',
        'setDeclaredFlatRootContainer',
        'primeDeclaredFlatRootContainer',
        'applyTombstoneDeletions',
        'backfillDeletedTombstones',
        'deletions.tombstones',
        '已同时从本机删掉',
        '按云端的删除记录删掉本机',
    ],
    'core/sync-merge.js': [
        "via: 'merge'",
        '没能写入本地',
        'conflictCount',
        'mergeTargetId',
        'buildMergeMessage',
        'skippedNoParent',
        'existingFolderIds',
        'crossZoneSkipped',
        '位置调整没落到位',
        'flatRootContainer',
        'wrapperSpliced',
        'remoteSpliced',
        'primeDeclaredFlatRootContainer',
        'localDeletedIds',
        'backfillDeletedTombstones',
        'mergeResult.tombstones',
        'mergedTombstones',
        'renameLocalNodes',
        '顺序没落到位',
        'mergeViaData(finalMergedData.bookmarks, tombstoneKeys)',
        'mergeViaData(mergedFlatList, tombstoneKeys2)',
    ],
    'lib/import.js': [
        'byBucket',
        'byUserTarget',
        'rootChildTitles',
        'zoneIds',
        'landedSample',
        'bucketKind',
        'flatRootChildId',
        'clearLocalFirst',
        'clearedBefore',
        'wrapperUnwrapped',
        'spliceWrapperFolders',
        'writeBucketChild',
        'deletedIds',
        'isTrueMerge',
        'wrapperSpliced',
        'wrapperSpliceFailures',
        'hasPendingDeletes',
        'underDeletedAncestor',
        'homeShellRemoved',
        'cloudHasHomeContent',
        'readHomeBridgeInUse',
    ],
    'lib/merge.js': [
        'zoneRoot',
        'isWrapperHere',
        'walkBucket',
        'bucketTitle',
        'getDeclaredFlatRootContainer',
        'declaredWrapper',
        'localDeletedIds',
        'buildTombstoneView',
        'prevSnapshotList',
        'renameLocalNodes',
        'localRenamed',
        '_decideRenameDiscard',
        'homeNodeId',
    ],
    'model/xbel-path.js': [
        'node.zoneRoot',
        'isVirtualRootChild',
    ],
    'model/tombstone.js': [
        'buildTombstoneView',
        'cleanExpired',
        'cleanFakeTombstones',
        'mergeTombstoneSources',
        'prevSnapshotList',
        '允许遗忘',
    ],
    'core/sync-input.js': [
        'applyTombstoneDeletions',
        'backfillDeletedTombstones',
        'buildTombstoneView',
        'prevSnapshotList',
        'topIds',
    ],
    'popup.html': [
        '增量：云端新增的导入本机',
        '云端已删除的会先从本机删掉',
        'progress-line.ok',
        'insecureUrlHint',
        'width: 320px',
        '!max-width: 100vw',
        '!@media (max-width: 300px)',
        'name="viewport" content="width=device-width',
        'html.host-mobile body',
        'icon-btn svg',
        'M12 4.5v10',
        '!>⬇<',
        '!>⬆<',
        '!>⟳<',
    ],
    'lib/webdav.js': [
        'redactUrlForLog',
    ],
}
